/**
 * Generated by orval v8.18.0 🍺
 * Do not edit manually.
 * Api
 * Vyapaar AI API Specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * Syncs Firebase authenticated user properties into PostgreSQL and configures default organization.
 * @summary Sync User Auth Profile
 */
export const SyncUserBody = zod.object({
  "id": zod.string(),
  "email": zod.string(),
  "displayName": zod.string().optional()
})

export const SyncUserResponse = zod.object({
  "success": zod.boolean().optional(),
  "user": zod.object({

}).passthrough().optional(),
  "organization": zod.object({

}).passthrough().optional(),
  "branch": zod.object({

}).passthrough().optional()
})


/**
 * Retrieves all organizations the authenticated user is a member of.
 * @summary List User Organizations
 */
export const ListOrganizationsResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "createdAt": zod.coerce.date().optional()
})
export const ListOrganizationsResponse = zod.array(ListOrganizationsResponseItem)


/**
 * Creates a new business organization tenant.
 * @summary Create Organization
 */
export const CreateOrganizationBody = zod.object({
  "name": zod.string()
})

export const CreateOrganizationResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "createdAt": zod.coerce.date().optional()
})


/**
 * Selects active organization profile.
 * @summary Switch Active Organization
 */
export const SwitchOrganizationParams = zod.object({
  "orgId": zod.coerce.number()
})

export const SwitchOrganizationResponse = zod.object({
  "success": zod.boolean().optional(),
  "orgId": zod.number().optional()
})


/**
 * Lists branches in active organization.
 * @summary List Branches
 */
export const ListBranchesQueryParams = zod.object({
  "orgId": zod.coerce.number()
})

export const ListBranchesResponseItem = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "name": zod.string(),
  "location": zod.string().optional()
})
export const ListBranchesResponse = zod.array(ListBranchesResponseItem)


/**
 * Creates a new branch for the active organization.
 * @summary Create Branch
 */
export const CreateBranchBody = zod.object({
  "orgId": zod.number(),
  "name": zod.string(),
  "location": zod.string().optional()
})

export const CreateBranchResponse = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "name": zod.string(),
  "location": zod.string().optional()
})


/**
 * Retrieves active organization business settings and branding details.
 * @summary Fetch Business Profile
 */
export const GetBusinessProfileQueryParams = zod.object({
  "orgId": zod.coerce.number()
})

export const GetBusinessProfileResponse = zod.object({
  "orgId": zod.number(),
  "logoUrl": zod.string().optional(),
  "tagline": zod.string().optional(),
  "primaryColor": zod.string().optional(),
  "shortDescription": zod.string().optional(),
  "category": zod.string().optional(),
  "phone": zod.string().optional(),
  "address": zod.string().optional(),
  "businessHours": zod.object({

}).passthrough().optional()
})


/**
 * Updates branding configurations, address, and business hours.
 * @summary Update Business Profile
 */
export const UpdateBusinessProfileBody = zod.object({
  "orgId": zod.number(),
  "logoUrl": zod.string().optional(),
  "tagline": zod.string().optional(),
  "primaryColor": zod.string().optional(),
  "shortDescription": zod.string().optional(),
  "category": zod.string().optional(),
  "phone": zod.string().optional(),
  "address": zod.string().optional(),
  "businessHours": zod.object({

}).passthrough().optional()
})

export const UpdateBusinessProfileResponse = zod.object({
  "orgId": zod.number(),
  "logoUrl": zod.string().optional(),
  "tagline": zod.string().optional(),
  "primaryColor": zod.string().optional(),
  "shortDescription": zod.string().optional(),
  "category": zod.string().optional(),
  "phone": zod.string().optional(),
  "address": zod.string().optional(),
  "businessHours": zod.object({

}).passthrough().optional()
})


/**
 * Retrieves customers associated with the active organization.
 * @summary List Customers
 */
export const ListCustomersQueryParams = zod.object({
  "orgId": zod.coerce.number()
})

export const ListCustomersResponseItem = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "branchId": zod.number().optional(),
  "name": zod.string(),
  "email": zod.string().optional(),
  "phone": zod.string().optional(),
  "notes": zod.string().optional()
})
export const ListCustomersResponse = zod.array(ListCustomersResponseItem)


/**
 * Adds a new customer profile.
 * @summary Create Customer
 */
export const CreateCustomerBody = zod.object({
  "orgId": zod.number(),
  "branchId": zod.number().optional(),
  "name": zod.string(),
  "email": zod.string().optional(),
  "phone": zod.string().optional(),
  "notes": zod.string().optional()
})

export const CreateCustomerResponse = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "branchId": zod.number().optional(),
  "name": zod.string(),
  "email": zod.string().optional(),
  "phone": zod.string().optional(),
  "notes": zod.string().optional()
})


/**
 * Retrieves sales leads and pipelines.
 * @summary List Leads
 */
export const ListLeadsQueryParams = zod.object({
  "orgId": zod.coerce.number()
})

export const ListLeadsResponseItem = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "branchId": zod.number().optional(),
  "customerId": zod.number().optional(),
  "source": zod.string().optional(),
  "status": zod.string(),
  "notes": zod.string().optional(),
  "assignedTo": zod.string().optional(),
  "createdAt": zod.coerce.date().optional()
})
export const ListLeadsResponse = zod.array(ListLeadsResponseItem)


/**
 * Inserts a new lead card.
 * @summary Create Lead
 */
export const CreateLeadBody = zod.object({
  "orgId": zod.number(),
  "branchId": zod.number().optional(),
  "customerId": zod.number().optional(),
  "source": zod.string().optional(),
  "status": zod.string().optional(),
  "notes": zod.string().optional(),
  "assignedTo": zod.string().optional()
})

export const CreateLeadResponse = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "branchId": zod.number().optional(),
  "customerId": zod.number().optional(),
  "source": zod.string().optional(),
  "status": zod.string(),
  "notes": zod.string().optional(),
  "assignedTo": zod.string().optional(),
  "createdAt": zod.coerce.date().optional()
})


/**
 * Updates status stage of a sales lead.
 * @summary Update Lead Pipeline Stage
 */
export const UpdateLeadStatusParams = zod.object({
  "leadId": zod.coerce.number()
})

export const UpdateLeadStatusBody = zod.object({
  "status": zod.string()
})

export const UpdateLeadStatusResponse = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "branchId": zod.number().optional(),
  "customerId": zod.number().optional(),
  "source": zod.string().optional(),
  "status": zod.string(),
  "notes": zod.string().optional(),
  "assignedTo": zod.string().optional(),
  "createdAt": zod.coerce.date().optional()
})


/**
 * Retrieves contact submissions.
 * @summary List Public Site Inquiries
 */
export const ListInquiriesQueryParams = zod.object({
  "orgId": zod.coerce.number()
})

export const ListInquiriesResponseItem = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "branchId": zod.number().optional(),
  "name": zod.string(),
  "email": zod.string().optional(),
  "phone": zod.string().optional(),
  "message": zod.string().optional(),
  "status": zod.string().optional(),
  "createdAt": zod.coerce.date().optional()
})
export const ListInquiriesResponse = zod.array(ListInquiriesResponseItem)


/**
 * Captures inquiries submitted by external clients on the business mini website.
 * @summary Public Submit Inquiry
 */
export const SubmitInquiryBody = zod.object({
  "orgId": zod.number(),
  "name": zod.string(),
  "email": zod.string().optional(),
  "phone": zod.string().optional(),
  "message": zod.string().optional()
})

export const SubmitInquiryResponse = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "branchId": zod.number().optional(),
  "name": zod.string(),
  "email": zod.string().optional(),
  "phone": zod.string().optional(),
  "message": zod.string().optional(),
  "status": zod.string().optional(),
  "createdAt": zod.coerce.date().optional()
})


/**
 * Lists follow-up operational tasks.
 * @summary List Tasks
 */
export const ListTasksQueryParams = zod.object({
  "orgId": zod.coerce.number()
})

export const ListTasksResponseItem = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "branchId": zod.number().optional(),
  "title": zod.string(),
  "description": zod.string().optional(),
  "status": zod.string(),
  "dueDate": zod.coerce.date().optional(),
  "assignedTo": zod.string().optional()
})
export const ListTasksResponse = zod.array(ListTasksResponseItem)


/**
 * Creates a follow-up task.
 * @summary Create Task
 */
export const CreateTaskBody = zod.object({
  "orgId": zod.number(),
  "branchId": zod.number().optional(),
  "title": zod.string(),
  "description": zod.string().optional(),
  "status": zod.string().optional(),
  "dueDate": zod.coerce.date().optional(),
  "assignedTo": zod.string().optional()
})

export const CreateTaskResponse = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "branchId": zod.number().optional(),
  "title": zod.string(),
  "description": zod.string().optional(),
  "status": zod.string(),
  "dueDate": zod.coerce.date().optional(),
  "assignedTo": zod.string().optional()
})


/**
 * Retrieves catalog products.
 * @summary List Products
 */
export const ListProductsQueryParams = zod.object({
  "orgId": zod.coerce.number()
})

export const ListProductsResponseItem = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "name": zod.string(),
  "description": zod.string().optional(),
  "price": zod.number(),
  "sku": zod.string().optional(),
  "stock": zod.number().optional(),
  "category": zod.string().optional(),
  "imageUrl": zod.string().optional()
})
export const ListProductsResponse = zod.array(ListProductsResponseItem)


/**
 * Adds a new catalog product.
 * @summary Create Product
 */
export const CreateProductBody = zod.object({
  "orgId": zod.number(),
  "name": zod.string(),
  "description": zod.string().optional(),
  "price": zod.number(),
  "sku": zod.string().optional(),
  "stock": zod.number().optional(),
  "category": zod.string().optional(),
  "imageUrl": zod.string().optional()
})

export const CreateProductResponse = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "name": zod.string(),
  "description": zod.string().optional(),
  "price": zod.number(),
  "sku": zod.string().optional(),
  "stock": zod.number().optional(),
  "category": zod.string().optional(),
  "imageUrl": zod.string().optional()
})


/**
 * Retrieves catalog services.
 * @summary List Services
 */
export const ListServicesQueryParams = zod.object({
  "orgId": zod.coerce.number()
})

export const ListServicesResponseItem = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "name": zod.string(),
  "description": zod.string().optional(),
  "price": zod.number(),
  "duration": zod.number().optional()
})
export const ListServicesResponse = zod.array(ListServicesResponseItem)


/**
 * Adds a new catalog service.
 * @summary Create Service
 */
export const CreateServiceBody = zod.object({
  "orgId": zod.number(),
  "name": zod.string(),
  "description": zod.string().optional(),
  "price": zod.number(),
  "duration": zod.number().optional()
})

export const CreateServiceResponse = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "name": zod.string(),
  "description": zod.string().optional(),
  "price": zod.number(),
  "duration": zod.number().optional()
})


/**
 * Retrieves customer orders and transaction history.
 * @summary List Orders
 */
export const ListOrdersQueryParams = zod.object({
  "orgId": zod.coerce.number()
})

export const ListOrdersResponseItem = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "branchId": zod.number().optional(),
  "customerId": zod.number().optional(),
  "status": zod.string(),
  "totalAmount": zod.number(),
  "paymentStatus": zod.string().optional(),
  "paymentMethod": zod.string().optional(),
  "type": zod.string().optional(),
  "notes": zod.string().optional(),
  "createdAt": zod.coerce.date().optional()
})
export const ListOrdersResponse = zod.array(ListOrdersResponseItem)


/**
 * Places a new customer order.
 * @summary Place Order
 */
export const CreateOrderBody = zod.object({
  "orgId": zod.number(),
  "branchId": zod.number().optional(),
  "customerId": zod.number().optional(),
  "status": zod.string().optional(),
  "totalAmount": zod.number(),
  "paymentStatus": zod.string().optional(),
  "paymentMethod": zod.string().optional(),
  "type": zod.string().optional(),
  "items": zod.array(zod.object({
  "productId": zod.number().optional(),
  "serviceId": zod.number().optional(),
  "quantity": zod.number(),
  "price": zod.number()
}))
})

export const CreateOrderResponse = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "branchId": zod.number().optional(),
  "customerId": zod.number().optional(),
  "status": zod.string(),
  "totalAmount": zod.number(),
  "paymentStatus": zod.string().optional(),
  "paymentMethod": zod.string().optional(),
  "type": zod.string().optional(),
  "notes": zod.string().optional(),
  "createdAt": zod.coerce.date().optional()
})


/**
 * Lists appointments (clinics, hospitality bookings, consultations).
 * @summary List Appointments
 */
export const ListAppointmentsQueryParams = zod.object({
  "orgId": zod.coerce.number()
})

export const ListAppointmentsResponseItem = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "branchId": zod.number().optional(),
  "customerId": zod.number(),
  "serviceId": zod.number().optional(),
  "staffId": zod.number().optional(),
  "dateTime": zod.coerce.date(),
  "status": zod.string(),
  "notes": zod.string().optional()
})
export const ListAppointmentsResponse = zod.array(ListAppointmentsResponseItem)


/**
 * Schedules a new booking.
 * @summary Book Appointment
 */
export const CreateAppointmentBody = zod.object({
  "orgId": zod.number(),
  "branchId": zod.number().optional(),
  "customerId": zod.number(),
  "serviceId": zod.number().optional(),
  "staffId": zod.number().optional(),
  "dateTime": zod.coerce.date(),
  "notes": zod.string().optional()
})

export const CreateAppointmentResponse = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "branchId": zod.number().optional(),
  "customerId": zod.number(),
  "serviceId": zod.number().optional(),
  "staffId": zod.number().optional(),
  "dateTime": zod.coerce.date(),
  "status": zod.string(),
  "notes": zod.string().optional()
})


/**
 * Lists service tickets or tasks.
 * @summary List Support Tickets
 */
export const ListTicketsQueryParams = zod.object({
  "orgId": zod.coerce.number()
})

export const ListTicketsResponseItem = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "branchId": zod.number().optional(),
  "customerId": zod.number(),
  "title": zod.string(),
  "description": zod.string().optional(),
  "status": zod.string(),
  "priority": zod.string().optional(),
  "assignedTo": zod.string().optional()
})
export const ListTicketsResponse = zod.array(ListTicketsResponseItem)


/**
 * Enters a customer service ticket.
 * @summary Log Service Ticket
 */
export const CreateTicketBody = zod.object({
  "orgId": zod.number(),
  "branchId": zod.number().optional(),
  "customerId": zod.number(),
  "title": zod.string(),
  "description": zod.string().optional(),
  "priority": zod.string().optional(),
  "assignedTo": zod.string().optional()
})

export const CreateTicketResponse = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "branchId": zod.number().optional(),
  "customerId": zod.number(),
  "title": zod.string(),
  "description": zod.string().optional(),
  "status": zod.string(),
  "priority": zod.string().optional(),
  "assignedTo": zod.string().optional()
})


/**
 * Lists customer invoices.
 * @summary List Invoices
 */
export const ListInvoicesQueryParams = zod.object({
  "orgId": zod.coerce.number()
})

export const ListInvoicesResponseItem = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "branchId": zod.number().optional(),
  "orderId": zod.number().optional(),
  "customerId": zod.number(),
  "invoiceNumber": zod.string(),
  "dueDate": zod.coerce.date().optional(),
  "status": zod.string(),
  "subtotal": zod.number(),
  "tax": zod.number().optional(),
  "discount": zod.number().optional(),
  "total": zod.number()
})
export const ListInvoicesResponse = zod.array(ListInvoicesResponseItem)


/**
 * Constructs a new invoice.
 * @summary Generate Invoice
 */
export const CreateInvoiceBody = zod.object({
  "orgId": zod.number(),
  "branchId": zod.number().optional(),
  "orderId": zod.number().optional(),
  "customerId": zod.number(),
  "invoiceNumber": zod.string(),
  "dueDate": zod.coerce.date().optional(),
  "subtotal": zod.number(),
  "tax": zod.number().optional(),
  "discount": zod.number().optional(),
  "total": zod.number()
})

export const CreateInvoiceResponse = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "branchId": zod.number().optional(),
  "orderId": zod.number().optional(),
  "customerId": zod.number(),
  "invoiceNumber": zod.string(),
  "dueDate": zod.coerce.date().optional(),
  "status": zod.string(),
  "subtotal": zod.number(),
  "tax": zod.number().optional(),
  "discount": zod.number().optional(),
  "total": zod.number()
})


/**
 * Retrieves transaction receipt history.
 * @summary List Payments
 */
export const ListPaymentsQueryParams = zod.object({
  "orgId": zod.coerce.number()
})

export const ListPaymentsResponseItem = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "invoiceId": zod.number().optional(),
  "orderId": zod.number().optional(),
  "amount": zod.number(),
  "paymentMethod": zod.string(),
  "transactionRef": zod.string().optional(),
  "status": zod.string(),
  "createdAt": zod.coerce.date().optional()
})
export const ListPaymentsResponse = zod.array(ListPaymentsResponseItem)


/**
 * Saves a payment receipt (e.g. cash, cards, bank, or UPI settlement).
 * @summary Record Payment Transaction
 */
export const RecordPaymentBody = zod.object({
  "orgId": zod.number(),
  "invoiceId": zod.number().optional(),
  "orderId": zod.number().optional(),
  "amount": zod.number(),
  "paymentMethod": zod.string(),
  "transactionRef": zod.string().optional(),
  "status": zod.string().optional()
})

export const RecordPaymentResponse = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "invoiceId": zod.number().optional(),
  "orderId": zod.number().optional(),
  "amount": zod.number(),
  "paymentMethod": zod.string(),
  "transactionRef": zod.string().optional(),
  "status": zod.string(),
  "createdAt": zod.coerce.date().optional()
})


/**
 * Lists social or message outreach logs.
 * @summary List Campaigns
 */
export const ListCampaignsQueryParams = zod.object({
  "orgId": zod.coerce.number()
})

export const ListCampaignsResponseItem = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "name": zod.string(),
  "type": zod.string(),
  "content": zod.string().optional(),
  "status": zod.string()
})
export const ListCampaignsResponse = zod.array(ListCampaignsResponseItem)


/**
 * Registers a marketing campaign.
 * @summary Create Campaign
 */
export const CreateCampaignBody = zod.object({
  "orgId": zod.number(),
  "name": zod.string(),
  "type": zod.string(),
  "content": zod.string().optional()
})

export const CreateCampaignResponse = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "name": zod.string(),
  "type": zod.string(),
  "content": zod.string().optional(),
  "status": zod.string()
})


/**
 * Core endpoint to consult with the AI Copilot. Uses message history to structure context-aware business recommendations.
 * @summary Conversational Copilot Chat
 */
export const CopilotChatBody = zod.object({
  "userId": zod.string(),
  "message": zod.string()
})

export const CopilotChatResponse = zod.object({
  "reply": zod.string().optional(),
  "suggestions": zod.array(zod.string()).optional()
})


/**
 * Analyzes answers to compile industry presets, digital maturity details, and activated app modules.
 * @summary Onboarding Optimization Analyzer
 */
export const CopilotOnboardingBody = zod.object({
  "businessName": zod.string(),
  "businessType": zod.string(),
  "serviceType": zod.string(),
  "language": zod.string().optional()
})

export const CopilotOnboardingResponse = zod.object({
  "industryType": zod.string().optional(),
  "maturityScore": zod.number().optional(),
  "modules": zod.array(zod.string()).optional(),
  "tagline": zod.string().optional(),
  "primaryColor": zod.string().optional(),
  "description": zod.string().optional()
})


/**
 * Securely generates a completion response from the backend OpenAI client.
 * @summary Get OpenAI Chat Completion
 */
export const GetOpenAICompletionBody = zod.object({
  "messages": zod.array(zod.object({
  "role": zod.enum(['system', 'user', 'assistant']),
  "content": zod.string()
}))
})

export const GetOpenAICompletionResponse = zod.object({
  "choices": zod.array(zod.object({
  "message": zod.object({
  "role": zod.string(),
  "content": zod.string()
})
}))
})


/**
 * Uploads a bill/invoice image and extracts lines, quantities, prices, and vendor info via multimodal AI.
 * @summary Extract Invoice Items via OCR
 */
export const OcrInvoiceBody = zod.object({
  "image": zod.instanceof(File)
})

export const OcrInvoiceResponse = zod.object({
  "vendorName": zod.string().optional(),
  "date": zod.string().optional(),
  "lineItems": zod.array(zod.object({
  "name": zod.string(),
  "quantity": zod.number(),
  "price": zod.number(),
  "total": zod.number().optional()
})),
  "total": zod.number()
})


/**
 * Retrieves core KPIs, sales, CRM pipeline conversion numbers, and active comparisons.
 * @summary Get Analytics Dashboard Stats
 */
export const GetAnalyticsDashboardQueryParams = zod.object({
  "orgId": zod.coerce.number()
})

export const GetAnalyticsDashboardResponse = zod.object({
  "revenueToday": zod.number(),
  "revenueMonthly": zod.number(),
  "ordersTotal": zod.number(),
  "customersCount": zod.number(),
  "salesHistory": zod.array(zod.object({
  "label": zod.string().optional(),
  "val": zod.number().optional()
})).optional(),
  "leadsHistory": zod.array(zod.object({
  "status": zod.string().optional(),
  "count": zod.number().optional()
})).optional()
})


/**
 * Flags products likely to stock out in the next N days based on sales velocity.
 * @summary Predict Product Stockout Risks
 */
export const GetInventoryForecastQueryParams = zod.object({
  "orgId": zod.coerce.number(),
  "days": zod.coerce.number().optional()
})

export const GetInventoryForecastResponseItem = zod.object({
  "productId": zod.number(),
  "name": zod.string(),
  "currentStock": zod.number(),
  "velocity": zod.number(),
  "daysRemaining": zod.number(),
  "riskLevel": zod.string()
})
export const GetInventoryForecastResponse = zod.array(GetInventoryForecastResponseItem)


/**
 * Linear trend revenue forecasting projection with merchant warning caveats.
 * @summary Forecast Next Month's Revenue
 */
export const GetRevenueForecastQueryParams = zod.object({
  "orgId": zod.coerce.number()
})

export const GetRevenueForecastResponse = zod.object({
  "projectedRevenue": zod.number(),
  "confidenceLevel": zod.string(),
  "caveat": zod.string(),
  "projectedMonth": zod.string(),
  "historicalTrend": zod.array(zod.object({
  "month": zod.string(),
  "revenue": zod.number()
}))
})


/**
 * Uploads a PDF or text catalog file, generates embeddings, and indexes chunks.
 * @summary Upload Knowledge File
 */
export const UploadKnowledgeFileQueryParams = zod.object({
  "orgId": zod.coerce.number()
})

export const UploadKnowledgeFileBody = zod.object({
  "file": zod.instanceof(File)
})

export const UploadKnowledgeFileResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string(),
  "documentId": zod.number()
})


/**
 * Query the scoped RAG knowledge base using a natural-language question.
 * @summary Query Knowledge Base
 */
export const QueryKnowledgeBody = zod.object({
  "question": zod.string(),
  "orgId": zod.number()
})

export const QueryKnowledgeResponse = zod.object({
  "answer": zod.string(),
  "sources": zod.array(zod.object({
  "id": zod.number(),
  "filename": zod.string(),
  "contentText": zod.string(),
  "similarity": zod.number()
}))
})


/**
 * Retrieves the catalog files list.
 * @summary List Knowledge Documents
 */
export const ListKnowledgeDocumentsQueryParams = zod.object({
  "orgId": zod.coerce.number()
})

export const ListKnowledgeDocumentsResponseItem = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "filename": zod.string(),
  "createdAt": zod.coerce.date().optional()
})
export const ListKnowledgeDocumentsResponse = zod.array(ListKnowledgeDocumentsResponseItem)


/**
 * Handles challenge verification from the Meta Developer platform.
 * @summary Verify WhatsApp Webhook
 */
export const VerifyWhatsAppWebhookQueryParams = zod.object({
  "hub.mode": zod.coerce.string(),
  "hub.verify_token": zod.coerce.string(),
  "hub.challenge": zod.coerce.string()
})

export const VerifyWhatsAppWebhookResponse = zod.string()


/**
 * Receives and processes message hooks from WhatsApp API.
 * @summary Ingest WhatsApp Business Event
 */
export const ReceiveWhatsAppMessageBody = zod.object({

}).passthrough()

export const ReceiveWhatsAppMessageResponse = zod.object({

}).passthrough()


/**
 * Retrieves transaction history of AI replies.
 * @summary Get Audited WhatsApp Conversations
 */
export const GetWhatsAppLogsQueryParams = zod.object({
  "orgId": zod.coerce.number()
})

export const GetWhatsAppLogsResponseItem = zod.object({
  "id": zod.number(),
  "orgId": zod.number(),
  "senderPhone": zod.string(),
  "message": zod.string(),
  "reply": zod.string(),
  "intentDetected": zod.string(),
  "createdAt": zod.string().optional()
})
export const GetWhatsAppLogsResponse = zod.array(GetWhatsAppLogsResponseItem)


/**
 * Retrieves branch toggle configurations.
 * @summary Get WhatsApp Branch Auto-Reply Settings
 */
export const GetWhatsAppSettingsQueryParams = zod.object({
  "branchId": zod.coerce.number()
})

export const GetWhatsAppSettingsResponse = zod.object({
  "branchId": zod.number(),
  "autoReply": zod.boolean()
})


/**
 * Saves active/inactive settings.
 * @summary Toggle WhatsApp Auto-Reply
 */
export const UpdateWhatsAppSettingsBody = zod.object({
  "branchId": zod.number(),
  "autoReply": zod.boolean()
})

export const UpdateWhatsAppSettingsResponse = zod.object({
  "branchId": zod.number(),
  "autoReply": zod.boolean()
})
export * from './index';
